# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'PlotProjectsReactModule' do
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'PlotPlugin'
  # Pods for PlotProjectsReactModule

end
